### ISSUE TITLE
NotoTraditionalNushu have upem of 1024

### ISSUE THREAD

**Issue by behdad** [notofonts/nushu#2]
All other noto fonts have upem of 1000. These ones have 1024. I found by accident. Donno what the back story is.

**Comment by simoncozens** [comment]
I don't think it's a problem, though, is it?

**Comment by simoncozens** [comment]
I don't think we're going to fix this; I don't see any benefit to scaling the font. Consider it a test of different rendering environments. :-)

**Comment by behdad** [comment]
> I don't see any benefit to scaling the font

It's useful for merging fonts.

**Comment by simoncozens** [comment]
Hmm, that's potentially a good reason, but maybe you need a better merging workflow... ;-)(i.e., if fonts are *allowed* to have different UPMs, any software which relies on them having a certain UPM is broken.)
