### ISSUE TITLE
Traditional Nushu VF has interpolation issues in u1B1CE, u1B2F1

### ISSUE THREAD

**Issue by MY1L** [notofonts/nushu#7]
https://cdn.jsdelivr.net/gh/notofonts/notofonts.github.io/fonts/NotoTraditionalNushu/unhinted/variable-ttf/NotoTraditionalNushu[wght].ttf ←this，Version 2.003

当[wght]=300~700时，如图：
![image](https://user-images.githubusercontent.com/58043328/212882637-92fd39b5-f656-4860-bf78-d49dbd266ce1.png)（u1B1CE）
![image](https://user-images.githubusercontent.com/58043328/212882765-fd7ddc85-029c-428a-bf2b-233c1262bad5.png)（u1B2F1）

我没全部检查，可能还有其它错误没发现。另外，字体中包含的那些汉字是非可变的。

----

还有，字体似乎缺失了opentype特性，有3个无映射字形无法调用：
1. uni3002.locl
2. u1B2B3.001
3. uni4494.locl

**Comment by simoncozens** [comment]
Thank you for this report! We now have a way of checking for interpolation errors like this, and the two glyphs you have found are the only two glyphs which report errors. I will get them fixed.

I'm not sure what localisation is expected for the U+3002 and U+4494 glyph, but I will try to find out.

**Comment by MY1L** [comment]
v2.004(?) not release?

**Comment by simoncozens** [comment]
No, not yet. We are batching releases into quarters to help downstream users. A new Nushu release will probably happen in Q3.
